services:

  umati.server:
    image: cw.opcua.umati.server:latest
    environment:
      - TZ=Europe/Amsterdam
      # - OPCUA_SERVER_HOST=localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '4334:4334'
    networks:
      - umati.hackathon
    volumes:
      - ./nodeset:/usr/src/app/nodeset


networks:
  umati.hackathon:
